<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rethink_electric_gripper">
  <xacro:macro name="rethink_electric_gripper" params="side r_finger r_finger_slot r_finger_tip r_finger_grasp l_finger l_finger_slot l_finger_tip l_finger_grasp camera_frame male_holder">
    <xacro:property name="gripper_side" value="${side[0]}" scope="local"/>
    <!-- Base of end effector -->
    <link name="${side}_gripper_base">
      <visual>
        <origin rpy="${-pi/2} ${pi} 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://birl_gripper_description/meshes/electric_gripper/electric_gripper_base.DAE"/>
        </geometry>
      </visual>
      
      <collision>
        <origin rpy="${-pi/2} ${pi} 0" xyz="0.0 0.0 0"/>
        <geometry>
          <cylinder length="0.1" radius="0.029"/>
        </geometry>
        <material name="darkred">
          <color rgba=".5 .1 .1 1"/>
        </material>
        </collision>
    
    
      <inertial>
        <origin rpy="${-pi/2} ${pi} 0" xyz="0.0 0.0 0.0"/>
        <mass value="0.3"/>
        <inertia ixx="2e-08" ixy="0" ixz="0" iyy="3e-08" iyz="0" izz="2e-08"/>
      </inertial>
    </link>


        <!--camera frame  -->    
<!--        <link name="${side}_gripper_base1">
          <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
              <mesh filename="package://birl_gripper_description/meshes/electric_gripper/electric_gripper_base.dae"/>
            </geometry>
          </visual>
          <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0"/>
            <geometry>
              <mesh filename="package://birl_gripper_description/meshes/electric_gripper/electric_pa_gripper_base.stl"/>

            </geometry>
          </collision>
          <inertial>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
            <mass value="0.3"/>
            <inertia ixx="2e-08" ixy="0" ixz="0" iyy="3e-08" iyz="0" izz="2e-08"/>
          </inertial>
        </link>
-->

<!--camera frame joint -->
<!--
    <joint name="${side}_gripper_base_camera_frame" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${side}_hand"/>
      <child link="${side}_gripper_base1"/>
    </joint>
-->
<xacro:if value="${camera_frame}">    
  <link name="${side}_camera_frame">
    <inertial>
      <origin
          xyz="0.024842 -0.00021599 0.048722"
          rpy="0 0 0" />
      <mass
          value="0.08" />
      <inertia
          ixx="8.4498E-05"
          ixy="-1.8832E-09"
          ixz="1.705E-07"
          iyy="7.8484E-05"
          iyz="-2.2039E-07"
          izz="7.3534E-05" />
    </inertial>
    <visual>
      <origin
          xyz="0 0 0"
          rpy="0 0 0" />
      <geometry>
        <mesh
            filename="package://birl_gripper_description/meshes/male_camera/camera_frame.STL" />
      </geometry>
      <material
          name="">
        <color
            rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin
          xyz="0 0 0"
          rpy="0 0 0" />
      <geometry>
        <mesh
            filename="package://birl_gripper_description/meshes/male_camera/camera_frame.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="${side}_gripper_base_camera_frame" type="fixed">
    <origin rpy="0 0 ${pi}" xyz="0.020 0 0"/>
    <parent link="${side}_hand"/>
    <child link="${side}_camera_frame"/>
  </joint>
  <gazebo reference="${side}_camera_frame">
    <mu1>1000</mu1>
    <mu2>1000</mu2>
    <fdir1>0.0 0.0 1.0</fdir1>
    <kp>1e4</kp>
    <kd>1.0</kd>
    <material>Gazebo/Gold</material>
    <self_collide>1</self_collide>
  </gazebo>



      <joint name="${side}_pa_endpoint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.052"/>
      <parent link="${side}_gripper_base"/>
      <child link="${side}_pa_gripper"/>
    </joint>
    <!-- Electric Gripper Tip link -->
    <link name="${side}_pa_gripper">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/>
      </inertial>
    </link>
    
</xacro:if>

<!--<xacro:if value="${male_holder}">-->
<xacro:if value="${male_holder}">  
  <link
      name="${side}_male_holder">
    <inertial>
      <origin
          xyz="1.2757E-10 9.385E-11 -0.001967"
          rpy="0 0 0" />
      <mass
          value="0.0301" />
      <inertia
          ixx="9.4008E-06"
          ixy="-3.1962E-14"
          ixz="3.1794E-15"
          iyy="3.9813E-06"
          iyz="2.3567E-15"
          izz="1.3208E-05" />
    </inertial>
    <visual>
      <origin
          xyz="0 0 0"
          rpy="0 0 0" />
      <geometry>
        <mesh
            filename="package://birl_gripper_description/meshes/male_camera/male_holder.STL" />
      </geometry>
      <material
          name="">
        <color
            rgba="0 0.552 0 1" />
      </material>
    </visual>
    <collision>
      <origin
          xyz="0 0 0"
          rpy="0 0 0" />
      <geometry>
        <mesh
            filename="package://birl_gripper_description/meshes/male_camera/male_holder.STL" />
      </geometry>
    </collision>
  </link>
  <joint
      name="${side}_camera_frame_joint"
      type="fixed">
    <origin
        xyz="0.025 -0.00031879 0.076"
        rpy="4.7429E-14 8.4242E-30 1.4971E-16" />
    <parent
        link="${side}_camera_frame" />
    <child
        link="${side}_male_holder" />
    <axis
        xyz="0 0 0" />
  </joint>
  
  <gazebo reference="${side}_male_holder">
    <mu1>1000</mu1>
    <mu2>1000</mu2>
    <fdir1>0.0 0.0 1.0</fdir1>
    <kp>1e4</kp>
    <kd>1.0</kd>
    <material>Gazebo/Purple</material>
    <self_collide>1</self_collide>
  </gazebo>
</xacro:if>


    <!-- Left finger link -->
    <xacro:property name="finger_length" value="0.0" scope="global"/>
    <xacro:include filename="$(find birl_gripper_description)/urdf/electric_gripper/fingers/${l_finger}.xacro" />
    <xacro:finger_xacro gripper_side="${gripper_side}" finger_side="l" reflect="1" finger_tip="${l_finger_tip}" finger_grasp="${l_finger_grasp}"/>
    <xacro:property name="tip_finger_length" value="${finger_length}" scope="local"/>

    <!-- Right finger link -->
    <xacro:include filename="$(find birl_gripper_description)/urdf/electric_gripper/fingers/${r_finger}.xacro" />
    <xacro:finger_xacro gripper_side="${gripper_side}" finger_side="r" reflect="-1" finger_tip="${r_finger_tip}" finger_grasp="${r_finger_grasp}"/>
    <xacro:if value="${finger_length > tip_finger_length}">
        <xacro:property name="tip_finger_length" value="${finger_length}" scope="local"/>
    </xacro:if>

    <!-- Electric Gripper Base Joint -->
    <joint name="${side}_gripper_base" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.025"/>
      <parent link="${side}_hand"/>
      <child link="${side}_gripper_base"/>
    </joint>

    
    <!-- Electric Gripper Tip joint -->
    <joint name="${side}_endpoint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 ${tip_finger_length+0.02}"/>
      <parent link="${side}_gripper_base"/>
      <child link="${side}_gripper"/>
    </joint>
    <!-- Electric Gripper Tip link -->
    <link name="${side}_gripper">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/>
      </inertial>
    </link>

    <!-- Left finger -->
    <xacro:property name="l_finger_offset" value="${((l_finger_slot-1)*0.0095) -0.011}" scope="local"/>
    <joint name="${gripper_side}_gripper_l_finger_joint" type="prismatic">
      <origin rpy="0 0 0" xyz="0.0 ${l_finger_offset} 0.02"/>
      <axis xyz="0 1 0"/>
      <parent link="${side}_gripper_base"/>
      <child link="${gripper_side}_gripper_l_finger"/>
      <limit effort="20.0" lower="0.0" upper="0.020833" velocity="5.0"/>
      <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <!-- Right finger -->
    <xacro:property name="r_finger_offset" value="${((r_finger_slot-1)*-0.0095) +0.011}" scope="local"/>
    <joint name="${gripper_side}_gripper_r_finger_joint" type="prismatic">
      <origin rpy="0 0 0" xyz="0.0 ${r_finger_offset} 0.02"/>
      <axis xyz="0 1 0"/>
      <parent link="${side}_gripper_base"/>
      <child link="${gripper_side}_gripper_r_finger"/>
      <limit effort="20.0" lower="-0.020833" upper="0.0" velocity="5.0"/>
      <mimic joint="${gripper_side}_gripper_l_finger_joint" multiplier="-1.0"/>
      <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <transmission name="gripper_${side}1">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${gripper_side}_gripper_r_finger_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gripper_${gripper_side}1_motor1">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="gripper_${side}2">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${gripper_side}_gripper_l_finger_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gripper_${gripper_side}1_motor2">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <gazebo reference="${gripper_side}_gripper_r_finger_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>
    <gazebo reference="${gripper_side}_gripper_l_finger_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

  </xacro:macro>
</robot>

    
